// U3 has A0 connected high, and U5 has A2 connected high,
// so they're at addresses 1 and 4 respectively:
#define ADDR_U3 1
#define ADDR_U5 4

// Port expander pin assignments
// U#,GPIO,pin,cfg
// cfg: U = input pullup, I = input, O = output
#define KEYSWITCH_CHANNEL_1 U3,A,7,U
#define KEYSWITCH_CHANNEL_2 U3,A,6,U
#define KEYSWITCH_CHANNEL_3 U3,A,5,U
#define KEYSWITCH_CHANNEL_4 U3,A,4,U
#define KEYSWITCH_CHANNEL_5 U3,A,3,U
#define KEYSWITCH_CHANNEL_6 U3,A,2,U
#define KEYSWITCH_CHANNEL_7 U3,A,1,U
#define KEYSWITCH_CHANNEL_8 U3,A,0,U
// U3 port B is unused; available on H2

#define MAIN_FN U5,A,0,U // aka FN1
#define REAR_FN U5,A,1,U // aka FN2
#define NAV_UP  U5,A,2,U
#define NAV_DN  U5,A,3,U
#define NAV_OP  U5,A,4,U
#define NAV_XY  U5,A,5,U
//#define nc U5,A,6
#define USB_X_1 U5,A,7,O // toggle power: rising edge powers off, IF soft power is released

#define USB_X_2      U5,B,0,O // SmartKnob enable: active high
#define USB_X_3      U5,B,1,O // power LED: active high
#define PEDAL_RSIN   U5,B,2,U
#define PEDAL_DET    U5,B,3,I // pedal present: active high
#define PEDAL_TRCTRL U5,B,4,O
#define USB_X_4      U5,B,5,U // soft power: open-drain, pulls low when pressed
#define LCD_RESET    U5,B,6,O // specific timings needed for GT911 touch chip - BEWARE!
#define ADCS_RESET   U5,B,7,O

/*
 * Soft power
 * ==========
 * Unit powers up when (momentary) soft power button is pressed
 * Teensy then enables regulators, SmartKnob, power LED at suitable times
 * When user presses soft power, USB_X_4 goes low; WAIT for it to be released,
 * do any required housekeeping, THEN apply a positive edge to toggle power 
 * (USB_X_1) to switch PSU off.
 */

 /*
  * Since the port expanders are used to sense the RGB buttons, we'll map those here
  */

#define PCB4_LED   0
#define REAR_FN_LED  1
#define PCB3_LED   2
#define NAV_XY_LED   3
#define NAV_OP_LED   4
#define NAV_DN_LED   5
#define NAV_UP_LED   6
#define PCB2_LED   7
#define MAIN_FN_LED  8
#define PCB1_LED   9
#define KEYSW1_LED  10
#define KEYSW2_LED  11
#define KEYSW3_LED  12
#define KEYSW4_LED  13
#define KEYSW5_LED  14
#define KEYSW6_LED  15
#define KEYSW7_LED  16
#define KEYSW8_LED  17



// Generated by procExpanders.py from the above
// DO NOT HAND-EDIT!
class MCP23S17_SETTINGS
{
  public:
    struct U3
    {
        static const uint8_t
            ADDR   = 1,
            IODIRA = 0b1111'1111,
            GPPUA  = 0b1111'1111,
            IODIRB = 0b1111'1111,
            GPPUB  = 0b0000'0000;
    };

    struct U5
    {
        static const uint8_t
            ADDR   = 4,
            IODIRA = 0b0111'1111,
            GPPUA  = 0b0011'1111,
            IODIRB = 0b0010'1100,
            GPPUB  = 0b0010'0100;
    };
};

#if 0
extern ButtonLED buttonLED_PCB4;
extern ButtonLED buttonLED_REAR_FN;
extern ButtonLED buttonLED_PCB3;
extern ButtonLED buttonLED_NAV_XY;
extern ButtonLED buttonLED_NAV_OP;
extern ButtonLED buttonLED_NAV_DN;
extern ButtonLED buttonLED_NAV_UP;
extern ButtonLED buttonLED_PCB2;
extern ButtonLED buttonLED_MAIN_FN;
extern ButtonLED buttonLED_PCB1;
extern ButtonLED buttonLED_KEYSW1;
extern ButtonLED buttonLED_KEYSW2;
extern ButtonLED buttonLED_KEYSW3;
extern ButtonLED buttonLED_KEYSW4;
extern ButtonLED buttonLED_KEYSW5;
extern ButtonLED buttonLED_KEYSW6;
extern ButtonLED buttonLED_KEYSW7;
extern ButtonLED buttonLED_KEYSW8;
#endif 

#if defined(CREATE_BUTTON_LEDS)
ButtonLED buttonLED_PCB4{buttonLEDstring, buttonLEDmemory, 0};
ButtonLED buttonLED_REAR_FN{buttonLEDstring, buttonLEDmemory, 1};
ButtonLED buttonLED_PCB3{buttonLEDstring, buttonLEDmemory, 2};
ButtonLED buttonLED_NAV_XY{buttonLEDstring, buttonLEDmemory, 3};
ButtonLED buttonLED_NAV_OP{buttonLEDstring, buttonLEDmemory, 4};
ButtonLED buttonLED_NAV_DN{buttonLEDstring, buttonLEDmemory, 5};
ButtonLED buttonLED_NAV_UP{buttonLEDstring, buttonLEDmemory, 6};
ButtonLED buttonLED_PCB2{buttonLEDstring, buttonLEDmemory, 7};
ButtonLED buttonLED_MAIN_FN{buttonLEDstring, buttonLEDmemory, 8};
ButtonLED buttonLED_PCB1{buttonLEDstring, buttonLEDmemory, 9};
ButtonLED buttonLED_KEYSW1{buttonLEDstring, buttonLEDmemory, 10};
ButtonLED buttonLED_KEYSW2{buttonLEDstring, buttonLEDmemory, 11};
ButtonLED buttonLED_KEYSW3{buttonLEDstring, buttonLEDmemory, 12};
ButtonLED buttonLED_KEYSW4{buttonLEDstring, buttonLEDmemory, 13};
ButtonLED buttonLED_KEYSW5{buttonLEDstring, buttonLEDmemory, 14};
ButtonLED buttonLED_KEYSW6{buttonLEDstring, buttonLEDmemory, 15};
ButtonLED buttonLED_KEYSW7{buttonLEDstring, buttonLEDmemory, 16};
ButtonLED buttonLED_KEYSW8{buttonLEDstring, buttonLEDmemory, 17};
#endif // defined(CREATE_BUTTON_LEDS)
#undef CREATE_BUTTON_LEDS    
